# Generated by Django 6.0.5 on 2026-05-12 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryexitlog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_logs', to='parking.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingfloor',
            unique_together={('lot', 'floor_number')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('zone', 'slot_number')},
        ),
    ]
