services:
  - type: web
    name: smart-parking-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    healthCheckPath: /admin/login/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
