databases:
  - name: smart-parking-db
    plan: free
    region: oregon

services:
  - type: web
    name: smart-parking-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py seed && python manage.py create_admin && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    healthCheckPath: /admin/login/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-parking-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://smart-parking-frontend-theta.vercel.app"
      - key: FRONTEND_URL
        value: "https://smart-parking-frontend-theta.vercel.app"
