# Generated by Django 6.0.5 on 2026-05-12 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('slot', 'Slot Recommendation'), ('route', 'Route Suggestion'), ('time', 'Time Suggestion')], default='slot', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True)),
                ('context_data', models.JSONField(default=dict)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
