# Generated by Django 6.0.5 on 2026-05-15 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_initial'),
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('cnn', 'CNN (MobileNetV2)'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM Forecaster')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('epochs', models.IntegerField(blank=True, null=True)),
                ('train_metric', models.FloatField(blank=True, null=True)),
                ('val_metric', models.FloatField(blank=True, null=True)),
                ('checkpoint', models.CharField(blank=True, max_length=255)),
                ('datasets_used', models.JSONField(default=list)),
                ('extra', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ai_training_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OccupancyForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_hour_0', models.FloatField()),
                ('forecast_hour_1', models.FloatField()),
                ('forecast_hour_2', models.FloatField()),
                ('forecast_hour_3', models.FloatField()),
                ('base_hour', models.IntegerField()),
                ('confidence', models.FloatField(default=0.8)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='parking.parkinglot')),
            ],
            options={
                'db_table': 'ai_occupancy_forecasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
