# Generated by Django 6.0.5 on 2026-05-12 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('alert', 'Alert'), ('promo', 'Promotion'), ('system', 'System')], default='system', max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App'), ('sms', 'SMS')], default='in_app', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
